version: '3.8'

services:
  mediasoup-server:
    # Build the server from the local Dockerfile in the ./server directory.
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      # Expose the HTTP/Socket.IO port.
      - "4001:4001"
      # Expose a wide range of UDP ports for WebRTC RTP streams.
      # This is crucial for media to be shared between peers.
      - "40000-41000:40000-41000/udp"
    volumes:
      # Mount the local server directory to the container for live reloading.
      - ./server:/app
      # This volume prevents node_modules from being overwritten.
      - /app/node_modules
    environment:
      # The announced IP is what the client sees and connects to.
      # host.docker.internal resolves to the host machine's IP.
      MEDIASOUP_ANNOUNCED_IP: "host.docker.internal"
      # The listen IP must be 0.0.0.0 to listen on all interfaces within the container.
      # This allows internal communication (e.g., with FFmpeg).
      MEDIASOUP_LISTEN_IP: "0.0.0.0"
      MEDIASOUP_MIN_PORT: 40000
      MEDIASOUP_MAX_PORT: 41000
      PORT: 4001
      NODE_ENV: production
    extra_hosts:
      # This is a critical configuration to ensure host.docker.internal works correctly.
      - "host.docker.internal:host-gateway"
    restart: unless-stopped