
version: '3.8'

services:
  mediasoup-server:
    build:
      context: ./server 
      dockerfile: Dockerfile 
    ports:
      - "4001:4001" 
      - "40000-41000:40000-41000/udp"
      - "40000-41000:40000-41000/tcp"
    volumes:
     
      - ./server:/app
      - /app/node_modules 
    environment:
     
      NODE_ENV: production
      MEDIASOUP_ANNOUNCED_IP: "host.docker.internal"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped 
    