# docker-compose.yml
version: '3.8'

services:
  mediasoup-server:
    build:
      context: ./server 
      dockerfile: Dockerfile 
    ports:
      - "4001:4001" 
      - "40000-41000:40000-41000/udp"
      - "40000-41000:40000-41000/tcp"
    volumes:
     
      - ./server:/app # Mount your server code for easier development (optional)
      - /app/node_modules # Prevent host node_modules from overwriting container's
    environment:
      # You can pass environment variables here if needed
      NODE_ENV: production
      MEDIASOUP_ANNOUNCED_IP: "host.docker.internal"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped # Automatically restart if it crashes
    